<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Album\Module'                       => __DIR__ . '/Module.php',
    'Album\Controller\AuthController'    => __DIR__ . '/src/Album/Controller/AuthController.php',
    'Album\Controller\SuccessController' => __DIR__ . '/src/Album/Controller/SuccessController.php',
    'Album\Model\MyAuthStorage'          => __DIR__ . '/src/Album/Model/MyAuthStorage.php',
    'Album\Model\User'                   => __DIR__ . '/src/Album/Model/User/User.php',
);
