<?php
$title = '添加加工记录';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$album = $form->get('title');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', '备注');

// This provides a default CSS class and placeholder text for the artist element:
$artist = $form->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', '员工');

$category = $form->get('category');
$category->setAttribute('class', 'form-control');
$category->setAttribute('placeholder', '请选择');

$num = $form->get('num');
$num->setAttribute('class', 'form-control');
$num->setAttribute('placeholder', '加工数量');

$type = $form->get('type');
$type->setAttribute('class', 'form-control');
$type->setAttribute('placeholder', '请选择');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('album', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($album) ?>
        <?= $this->formElement($album) ?>
        <?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($artist) ?>
        <?= $this->formElement($artist) ?>
        <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($category) ?>
        <?= $this->formElement($category) ?>
        <?= $this->formElementErrors()->render($category, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($num) ?>
        <?= $this->formElement($num) ?>
        <?= $this->formElementErrors()->render($num, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($type) ?>
        <?= $this->formElement($type) ?>
        <?= $this->formElementErrors()->render($type, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
