<div class="jumbotron">
    <h1>欢迎使用<span class="zf-green">加工工件计件系统</span></h1>

    <p>
        本系统的开发基于
        <a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">ZF Skeleton Application</a>.
        您的系统运行在 Zend Framework version <?= \Application\Module::VERSION ?> 基础上.
        本系统用于记录每日每位员工的加工工件数量，用于月终统计，结算工资。
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/micao/ptools" target="_blank">源代码位于 GitHub &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">记录工件</h3>
            </div>
            <div class="panel-body">
                <p>
                    正在制作中，请耐心等候。。。。。。
                </p>

                <p><a class="btn btn-success pull-right" href="#" target="_blank">去计件 &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">计算月终工资</h3>
            </div>
            <div class="panel-body">
                <p>
                    正在制作中，请耐心等候。。。。。。
                </p>

                <p><a class="btn btn-success pull-right" href="#" target="_blank">月结单 &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">工作量报告</h3>
            </div>
            <div class="panel-body">
                <p>
                    正在制作中，请耐心等候。。。。。。
                </p>

                <p><a class="btn btn-success pull-right" href="#" target="_blank">工作量报告 &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
